server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass server:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location /api {
        try_files $uri $uri/ /index.php?$query_string;
    }
}
.env.example
env# Laravel環境設定
APP_NAME=MyApp
APP_ENV=local
APP_KEY=
APP_DEBUG=true
APP_URL=http://localhost:8000

# データベース設定
DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=laravel_app
DB_USERNAME=laravel_user
DB_PASSWORD=laravel_pass

# Redis設定
REDIS_HOST=redis
REDIS_PASSWORD=null
REDIS_PORT=6379

# Sanctum設定
SANCTUM_STATEFUL_DOMAINS=localhost:3000

# フロントエンド設定
REACT_APP_API_URL=http://localhost:8000/api